language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
env:
  global:
    - secure: "rXlphzMgWoDyu4C4TTrAqRd0zscwQ4O5nIfIhKaUl86vKpexWKwAEkTAwMQpPULgOJl+k92lnG6VbQcD8oFVA1RC2a7VXauScD588FWMWOVBiJcrhWbxF4SOTkkCHZnL+GUTPZof4Ir9YRyJ3Gvmm8ak4SHQqocJqNPDY9IgmuSuFNX0HYs32+uGyiZOfG2y2+vBpyUMzTZDF25gDuOI9F3R432O/dSCX4BMB8xRJKKhOFi41ICEknq24+Sfr5AL+PPFiTHu37kXonqX+wVB9gAy8JpgKjhdGVjf5CUc3A7Fx+rhbbNthjVuAD5eBs8IWRl6DdYJ45uo0m6nUukbpfyFk5G1UBIICl/BOOsSi4VQBcjrmZqzIv5N5upGUNTD9Z/AC81hZxJmx6LzsKg5rc8h+La6F/2JbqIXt00WIF024Ks4MQZI3p2qtC5CF6JWFVDh/V66Jh7wcoVVn65g8klYkM6/nadcRdEMAOYh0KiCg3QImhK9aLVSy/z+q2jHcntxf5SChg9+1MQKRyytY7mLxLA+NSTABZlR/7dtIe4axVf0rQItgwVB+XmhUi0M9D9HmvDExHI0/yyKb3adyPAPwth6YsCre1A+SLgEaykI9BevUWGYEppTltGUqdpgiRuDORDdF1yvlNOygSByfskmnsJiW2VlUaXs1O+xmD8="
os:
  - osx